package com.google.android.gms.games.multiplayer.turnbased;

import com.google.android.gms.games.multiplayer.OnInvitationReceivedListener;

@Deprecated
public interface TurnBasedMultiplayerListener extends OnInvitationReceivedListener, OnTurnBasedMatchCanceledListener, OnTurnBasedMatchInitiatedListener, OnTurnBasedMatchLeftListener, OnTurnBasedMatchUpdateReceivedListener, OnTurnBasedMatchUpdatedListener, OnTurnBasedMatchesLoadedListener {
}
